chore(deps): update kube-rbac-proxy to v0.20.0
Turns out the runAsNonRoot issue we saw with v0.20.0 earlier is a
Docker Desktop issue. It does not reproduce on kind, for example. And
there is a workaround for Docker Desktop: pass an explicit user ID in
the container security context.

For context, without setting the explicit user ID, K8s on Docker Desktop
fails to start any pod with a kube-rbac-proxy container with:
    Error: container has runAsNonRoot and image will run as root
    (pod: "...", container: kube-rbac-proxy)

For reference, the underlying issue that makes this workaround
necessary is tracked here:
https://github.com/docker/for-mac/issues/7723