chore(deps): downgrade k8s.io/* packages to 0.32.4 again
Apparently upgrading k8s.io/client-go to 0.33.0 needs to wait for an
updated release from sigs.k8s.io/controller-runtime; the controller
tests do not compile currently:

pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/controller/controllertest/util.go:26:35:
cannot use &FakeInformer{} (value of type *FakeInformer) as
"k8s.io/client-go/tools/cache".SharedIndexInformer value in variable
declaration: *FakeInformer does not implement
"k8s.io/client-go/tools/cache".SharedIndexInformer (missing method AddEventHandlerWithOptions)